# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-24 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_faq_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='show_on_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='show_on_sponsors',
            field=models.BooleanField(default=False),
        ),
    ]
