# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-03 06:17
from __future__ import unicode_literals

from django.db import migrations


def copy_order(apps, schema_editor):
    Faq = apps.get_model('faqs', 'Faq')
    for faq in Faq.objects.all():
        faq.order = faq.ordering
        faq.save()

class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0005_auto_20180102_2214'),
    ]

    operations = [
      migrations.RunPython(copy_order),
    ]
