# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-20 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(default='', help_text='Employer name.', max_length=255)),
                ('contact_email', models.EmailField(default='', help_text='Not shared publicly. Be sure to use the email associated with your Paypal account.', max_length=255)),
                ('contact_phone', models.CharField(default='', help_text='Not shared publicly.', max_length=20)),
                ('display', models.BooleanField(default=False, help_text='Show this job posting on the site.')),
                ('logo', models.ImageField(blank=True, upload_to='logos')),
                ('url', models.SlugField()),
                ('details', models.TextField(help_text='Short and punchy text - 140 chars or less.', verbose_name='Summary')),
                ('lengthy_details', models.TextField(blank=True, help_text='The rest of the details.', verbose_name='Details')),
                ('link', models.CharField(default='', help_text='Add a link to apply for this job.', max_length=255)),
                ('background', models.CharField(blank=True, max_length=6)),
                ('level', models.IntegerField(choices=[(3500, 'Platinum'), (2000, 'Diamond'), (1500, 'Gold'), (1000, 'Silver'), (500, 'Bronze'), (0, 'None')], default=0)),
                ('location', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Job Details',
                'verbose_name_plural': 'Job Postings',
            },
        ),
    ]
