# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-03-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='details',
            field=models.TextField(help_text='Short and punchy text', verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='lengthy_details',
            field=models.TextField(blank=True, help_text='The rest of the details. Use markdown for bulleted lists, *italics*, etc.', verbose_name='Details'),
        ),
    ]
