# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-25 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorbenefits', '0002_auto_20180221_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='benefit_level',
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
        migrations.DeleteModel(
            name='BenefitLevel',
        ),
    ]
