# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-25 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsorbenefits', '0003_auto_20180324_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('text', models.CharField(help_text='Display table etc.', max_length=255)),
                ('diamond_text', models.CharField(default='', max_length=255)),
                ('gold_text', models.CharField(default='', max_length=255)),
                ('silver_text', models.CharField(default='', max_length=255)),
                ('bronze_text', models.CharField(default='', max_length=255)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
