# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-25 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorbenefits', '0004_benefitrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitrow',
            name='bronze_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='benefitrow',
            name='diamond_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='benefitrow',
            name='gold_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='benefitrow',
            name='silver_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
