# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorbenefits', '0005_auto_20180325_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnBenefitRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('price_text', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlaCarteBenefitRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('price_text', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
