# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorbenefits', '0006_addonbenefitrow_alacartebenefitrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alacartebenefitrow',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
