# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorbenefits', '0008_auto_20180528_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('text', models.CharField(help_text='Job slot, Logo, etc', max_length=255)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenefitApplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Number, description or checkmark', max_length=255)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorbenefits.Benefit')),
            ],
        ),
        migrations.CreateModel(
            name='ExplanationRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('text', models.CharField(help_text='Diversity, Recruiting, Etc.', max_length=255)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('text', models.CharField(help_text='Champion, Partner, Etc', max_length=255)),
                ('price_text', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorbenefits.SponsorCategory')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('text', models.CharField(help_text='Pre-conf, post conf, etc.', max_length=255)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BenefitRow',
        ),
        migrations.RemoveField(
            model_name='alacartebenefitrow',
            name='text',
        ),
        migrations.AddField(
            model_name='benefitapplies',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorbenefits.SponsorLevel'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorbenefits.SponsorPackage'),
        ),
    ]
