# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-17 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorbenefits', '0009_auto_20190408_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorcategory',
            options={'verbose_name_plural': 'Sponsor categories'},
        ),
    ]
