# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-24 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Text above the countdown')),
                ('date', models.DateTimeField(help_text='The date the countdown counts to')),
                ('cta', models.TextField(help_text='Text on the button below the countdown', verbose_name="Call to action")),
                ('link', models.TextField(help_text='Target of the button below the countdown')),
            ],
        ),
    ]
