# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-19 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Col3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_title', models.CharField(blank=True, max_length=255)),
                ('icon_1', models.CharField(blank=True, help_text='Choose from http://themes-pixeden.com/font-demos/7-stroke/', max_length=50)),
                ('title_1', models.CharField(blank=True, max_length=255)),
                ('content_1', models.TextField(blank=True)),
                ('icon_2', models.CharField(blank=True, max_length=50)),
                ('title_2', models.CharField(blank=True, max_length=255)),
                ('content_2', models.TextField(blank=True)),
                ('icon_3', models.CharField(blank=True, max_length=50)),
                ('title_3', models.CharField(blank=True, max_length=255)),
                ('content_3', models.TextField(blank=True)),
                ('show_title', models.BooleanField(default=True)),
            ],
        ),
    ]
