# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-19 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='category',
            field=models.CharField(choices=[('fundamentals', 'Fundamentals'), ('language internals', 'Language Internals'), ('all things web', 'All things Web'), ('dealing with data', 'Dealing with Data'), ('security', 'Security'), ('performant python', 'Performant Python'), ('scalable python', 'Scalable Python'), ('etc', '/etc')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='talk_links',
            field=models.CharField(choices=[('fundamentals', 'Fundamentals'), ('language internals', 'Language Internals'), ('all things web', 'All things Web'), ('dealing with data', 'Dealing with Data'), ('security', 'Security'), ('performant python', 'Performant Python'), ('scalable python', 'Scalable Python'), ('etc', '/etc')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='what_will_attendees_learn',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='category',
            field=models.CharField(choices=[('fundamentals', 'Fundamentals'), ('language internals', 'Language Internals'), ('all things web', 'All things Web'), ('dealing with data', 'Dealing with Data'), ('security', 'Security'), ('performant python', 'Performant Python'), ('scalable python', 'Scalable Python'), ('etc', '/etc')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='talk_links',
            field=models.CharField(choices=[('fundamentals', 'Fundamentals'), ('language internals', 'Language Internals'), ('all things web', 'All things Web'), ('dealing with data', 'Dealing with Data'), ('security', 'Security'), ('performant python', 'Performant Python'), ('scalable python', 'Scalable Python'), ('etc', '/etc')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='what_will_attendees_learn',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
