# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-21 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='category',
            field=models.IntegerField(choices=[(1, 'Fundamentals'), (2, 'Language Internals'), (3, 'All things Web'), (4, 'Dealing with Data'), (5, 'Security'), (6, 'Performant Python'), (7, 'Scalable Python'), (8, '/etc')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='category',
            field=models.IntegerField(choices=[(1, 'Fundamentals'), (2, 'Language Internals'), (3, 'All things Web'), (4, 'Dealing with Data'), (5, 'Security'), (6, 'Performant Python'), (7, 'Scalable Python'), (8, '/etc')], default=1),
            preserve_default=False,
        ),
    ]
