# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-17 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20170516_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='speaker_and_talk_history',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='speaker_and_talk_history',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
