# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-26 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20170614_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='category',
            field=models.CharField(choices=[('fundamentals', 'Fundamentals'), ('language internals', 'Language Internals'), ('all things web', 'All things Web'), ('dealing with data', 'Dealing with Data'), ('security', 'Security'), ('performant python', 'Performant Python'), ('scalable python', 'Scalable Python'), ('devops', 'DevOps'), ('etc', '/etc')], max_length=100),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='meetup_talk',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Maybe', 'Maybe'), ('No', 'No')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='speaker_website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='category',
            field=models.CharField(choices=[('fundamentals', 'Fundamentals'), ('language internals', 'Language Internals'), ('all things web', 'All things Web'), ('dealing with data', 'Dealing with Data'), ('security', 'Security'), ('performant python', 'Performant Python'), ('scalable python', 'Scalable Python'), ('devops', 'DevOps'), ('etc', '/etc')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='meetup_talk',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Maybe', 'Maybe'), ('No', 'No')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='speaker_website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
