# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-01 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_location_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
