# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-18 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_auto_20180228_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='category',
            field=models.CharField(choices=[('python fundamentals and language internals', 'Python fundamentals and language internals'), ('machine learning, ai, & all things data', 'Machine learning, AI, & all things data'), ('devops, automation, & testing', 'DevOps, automation, & testing'), ('hacking hardware with python', 'Hacking hardware with Python'), ('engineering a community', 'Engineering a community')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='category',
            field=models.CharField(choices=[('python fundamentals and language internals', 'Python fundamentals and language internals'), ('machine learning, ai, & all things data', 'Machine learning, AI, & all things data'), ('devops, automation, & testing', 'DevOps, automation, & testing'), ('hacking hardware with python', 'Hacking hardware with Python'), ('engineering a community', 'Engineering a community')], max_length=100),
        ),
    ]
