# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-18 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_auto_20180317_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='talk_length',
            field=models.IntegerField(choices=[(25, '25 minutes'), (40, '40 minutes')], default=25),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='talk_length',
            field=models.IntegerField(choices=[(25, '25 minutes'), (40, '40 minutes')], default=25),
        ),
    ]
