# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-19 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_auto_20180318_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, 'Novice'), (3, 'Intermediate'), (2, 'Advanced')]),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, 'Novice'), (3, 'Intermediate'), (2, 'Advanced')]),
        ),
    ]
