# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-19 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_auto_20180318_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='category',
            field=models.CharField(choices=[('python fundamentals & language internals', 'Python Fundamentals & Language Internals'), ('machine learning, ai, & all things data', 'Machine Learning, AI, & All things Data'), ('devops, automation, & testing', 'DevOps, Automation, & Testing'), ('dealing with speed, scale, & performance', 'Dealing with Speed, Scale, & Performance'), ('fun: hacking hardwareengineering a community ', 'Fun: Hacking Hardware/Engineering a Community ')], max_length=250),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='category',
            field=models.CharField(choices=[('python fundamentals & language internals', 'Python Fundamentals & Language Internals'), ('machine learning, ai, & all things data', 'Machine Learning, AI, & All things Data'), ('devops, automation, & testing', 'DevOps, Automation, & Testing'), ('dealing with speed, scale, & performance', 'Dealing with Speed, Scale, & Performance'), ('fun: hacking hardwareengineering a community ', 'Fun: Hacking Hardware/Engineering a Community ')], max_length=250),
        ),
    ]
