# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-28 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_auto_20180328_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talkproposal',
            old_name='category',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='tutorialproposal',
            old_name='category',
            new_name='themes',
        ),
    ]
