# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-30 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0018_auto_20180328_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='themes',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='themes',
            field=models.CharField(max_length=250),
        ),
    ]
