# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-28 02:45
from __future__ import unicode_literals

from django.db import migrations


THEME_CHOICES = {
    'python': ['Python Fundamentals & Popular Libraries'],
    'ai': ['Machine Learning, AI, & All things Data'],
    'automation': ['DevOps, Automation, & Testing'],
    'speed': ['Dealing with Speed, Scale, & Performance'],
    'community': ['Hacking Hardware', 'Engineering a Community'],
}
for slug, descriptions in THEME_CHOICES.items():
    for description in descriptions[:]:
        if '&' in description:
            descriptions.append(description.replace('&', 'and'))
        descriptions.append(description.lower().replace('/', ''))


def migrate_themes(Proposal, reverse=False):
    for proposal in Proposal.objects.all():
        theme = proposal.themes
        for slug, descriptions in THEME_CHOICES.items():
            if not reverse:
                for description in descriptions:
                    theme = theme.replace(description, slug)
            else:
                theme = theme.replace(slug, descriptions[0])
        if not reverse:
            theme = theme.replace(' ', '')
        proposal.themes = theme
        proposal.save()


def forward(apps, schema_editor):
    TalkProposal = apps.get_model('proposals', 'TalkProposal')
    migrate_themes(TalkProposal)
    TutorialProposal = apps.get_model('proposals', 'TutorialProposal')
    migrate_themes(TutorialProposal)


def reverse(apps, schema_editor):
    TalkProposal = apps.get_model('proposals', 'TalkProposal')
    migrate_themes(TalkProposal, reverse=True)
    TutorialProposal = apps.get_model('proposals', 'TutorialProposal')
    migrate_themes(TutorialProposal, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_auto_20180329_2044'),
    ]

    operations = [
            migrations.RunPython(forward, reverse),
    ]
