# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-17 04:39
from __future__ import unicode_literals

from django.db import migrations
from django.db import connection

db_name = connection.settings_dict['NAME']

def forwards(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
    migrations.RunSQL("ALTER DATABASE {} CHARACTER SET = utf8mb4 COLLATE utf8mb4_unicode_ci;".format(db_name))


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0020_slugify-themes'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
