# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-17 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_auto_20190616_2139'),
    ]

    operations = [
      migrations.RunSQL("ALTER TABLE symposion_proposals_proposalbase CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"),
    ]
