# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-23 23:48
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
    schema_editor.execute("ALTER TABLE symposion_schedule_presentation CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")



class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_auto_20190617_0810'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
