# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-07-01 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_auto_20190628_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')]),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='speaker_and_talk_history',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='what_attendees_will_learn',
            field=models.TextField(default='', blank=True),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')]),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='speaker_and_talk_history',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='what_attendees_will_learn',
            field=models.TextField(default='', blank=True),
        ),
    ]
