# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-21 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('text', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Menu Items',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('text', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('target', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='menu.MenuItem')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
