# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-22 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenuitem',
            options={'ordering': ('order',), 'verbose_name_plural': 'SubMenu Items'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='target',
            field=models.CharField(blank=True, help_text='Leave empty or set to _blank to open in new window', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='text',
            field=models.CharField(help_text='Display text for link', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(help_text='URL (/relative or http://domain.com)', max_length=255),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='target',
            field=models.CharField(blank=True, help_text='Leave empty or set to _blank to open in new window', max_length=50),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='text',
            field=models.CharField(help_text='Display text for link', max_length=255),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='url',
            field=models.TextField(help_text='URL (/relative or http://domain.com)', max_length=255),
        ),
    ]
