# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-22 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180221_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenuitem',
            name='url',
            field=models.CharField(help_text='URL (/relative or http://domain.com)', max_length=255),
        ),
    ]
