# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-21 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FeaturedSpeaker',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('speaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='symposion_speakers.Speaker')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
