# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-26 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_speakers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredspeaker',
            name='title',
        ),
        migrations.AddField(
            model_name='featuredspeaker',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
